# Generated by Django 5.0.4 on 2024-08-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('houseType', models.CharField(choices=[('single room', 'Singleroom'), ('bedsitter', 'Bedsitter'), ('one bedroom', 'Onebedroom'), ('two bedroom', 'Twobedroom'), ('three bedroom', 'Threebedroom'), ('four bedroom', 'Fourbedroom'), ('own compound', 'Owncompound')], default='single room', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('images', models.JSONField(max_length=1000, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
    ]
