# Generated by Django 5.0.4 on 2024-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='features',
            field=models.JSONField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
